Zap

diff --git a/.github/workflows/main_ccsecw2webapp.yml b/.github/workflows/main_ccsecw2webapp.yml
--- a/.github/workflows/main_ccsecw2webapp.yml
+++ b/.github/workflows/main_ccsecw2webapp.yml
@@ -1,4 +1,4 @@
-name: Build, Scan, and Deploy Container App to Azure Web App - ccsecw2webapp
+name: Pipeline to azure web app
 
 on:
   push:
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  build_and_scan:
+  Build:
     runs-on: ubuntu-latest
 
     steps:
@@ -23,43 +23,46 @@ jobs:
         username: ${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}
         password: ${{ secrets.AzureAppService_ContainerPassword_0b5bac57b0bd4ca2b524d5c48f14a083 }}
 
-    - name: Build container image
+    - name: Build Image
       id: build-image
       uses: docker/build-push-action@v2
       with:
         push: false 
         tags: ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}
         file: ./Dockerfile
+  
+  Synk_scan:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Run Snyk scan
+        run: |
+          docker pull snyk/snyk:docker
+          docker run --rm \
+            -v /var/run/docker.sock:/var/run/docker.sock \
+            -v ${{ github.workspace }}:/project \
+            -w /project \
+            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
+            snyk/snyk:docker snyk test \
+            --docker ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }} \
+            --file=./Dockerfile \
+            --severity-threshold=high \
+            --json > snyk_report.json || true  # Ignore the exit code to prevent job failure
 
-    - name: Run Snyk to check for vulnerabilities
-      run: |
-        docker pull snyk/snyk:docker
-        docker run --rm \
-          -v /var/run/docker.sock:/var/run/docker.sock \
-          -v ${{ github.workspace }}:/project \
-          -w /project \
-          -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
-          snyk/snyk:docker snyk test \
-          --docker ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }} \
-          --file=./Dockerfile \
-          --severity-threshold=high \
-          --json > snyk_report.json || true  # Ignore the exit code to prevent job failure
+      - name: Upload Snyk scan results
+        uses: actions/upload-artifact@v3
+        with:
+          name: snyk-scan-results
+          path: snyk_report.json
 
-    - name: Upload Snyk scan results
-      uses: actions/upload-artifact@v3
-      with:
-        name: snyk-scan-results
-        path: snyk_report.json
-
-    - name: Push container image to registry
-      uses: docker/build-push-action@v2
-      with:
-        push: true
-        tags: ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}
+      - name: Push container image to registry
+        uses: docker/build-push-action@v2
+        with:
+          push: true
+          tags: ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}
 
   deploy:
     runs-on: ubuntu-latest
-    needs: build_and_scan
+    needs: Synk_scan
     outputs:
       webapp-url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     steps:
@@ -73,7 +76,7 @@ jobs:
         images: 'ccsecw2reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_30fffea09cf74c74973f022931feb204 }}/myapp:${{ github.sha }}'
 
   zap_scan:
-    name: OWASP ZAP Full Scan
+    name: Run zap scan
     runs-on: ubuntu-latest
     needs: deploy
     steps:
